'''
DICHIARA UNA VARIABILE X CHE PUNTA AD UN OGGETTO INTERO DI VALORE 100
ESPRESSO IN NOTAZIONE DECIMALE
'''
x = 100
print(type(x))

'''
DICHIARA UNA VARIABILE Y CHE PUNTA AD UN OGGETTO INTERO DI VALORE 100
ESPRESSO IN NOTAZIONE BINARIA
'''
y = 0b1100100   # bin(100)
print(type(y))
print(y)

'''
DICHIARA UNA VARIABILE F CHE PUNTA AD UN OGGETTO FLOATING POINT
DI VALORE 975
'''
f = 975.0
print(type(f))

'''
DICHIARA UNA VARIABILE F CHE PUNTA AD UN OGGETTO FLOATING POINT
DI VALORE 975 IN NOTAZIONE ESPONENZIALE
'''
f = 9.75E2
print(type(f))
print(f)






