"""
CREA UNA TUPLA CONTENENTE I NUMERI 1 E 2 E ASSEGNALA ALLA VARIABILE T1
"""
t1 = 1, 2
print(t1)

"""
CREA UNA TUPLA CONTENENTE I NUMERI 3 E 4 E ASSEGNALA ALLA VARIABILE T2
"""
t2 = 3, 4
print(t2)

"""
CREA UNA LISTA MYLIST CHE HA COME ELEMENTI LE DUE TUPLE T1 E T2
"""
mylist = [t1, t2]
print(mylist)

"""
AGGIUNGI IN CODA ALLA LISTA UNA NUOVA TUPLA CONTENENTE I VALORI 5 E 6
"""
mylist.append((5, 6))
print(mylist)
